<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

$module = new PayqrButtonDefaultSettings();

$settings = array(
    array(
        "key" => "base-options",
        "name" => "Базовые настройки",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "",
    ),
    array(
        "key" => "handleUrl",
        "name" => "URL PayQR обработчика",
        "value" => $module->getHandlerUrl(),
        "possible_values" => array(),
        "changable" => "0",
        "published" => "1",
        "parent" => "base-options",
    ),
    array(
        "key" => "merchantID",
        "name" => "PayQR merchant ID",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "base-options",
    ),
    array(
        "key" => "secretKeyIn",
        "name" => "PayQR SecretKeyIn",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "base-options",
    ),
    array(
        "key" => "secretKeyOut",
        "name" => "PayQR SecretKeyOut",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "base-options",
    ),
    array(
        "key" => "logKey",
        "name" => "Ключ доступа к логам",
        "value" => $module->getLogKey(),
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "base-options",
    ),
    array(
        "key" => "logFilePath",
        "name" => "Путь к файлу логов",
        "value" => $module->getLogPath(),
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "base-options",
    ),
    array(
        "key" => "logUrl",
        "name" => "URL для просмотра логов",
        "value" => $module->getLogUrl(),
        "possible_values" => array(),
        "changable" => "0",
        "published" => "1",
        "parent" => "base-options",
    ),
    array(
        "key" => "button-options",
        "name" => "Настройки кнопки",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "",
    ),
    array(
        "key" => "button-show-on-cart",
        "name" => "Показывать кнопку PayQR на страничке корзины",
        "value" => "",
        "possible_values" => array("Нет", "Да"),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-options",
    ),
    array(
        "key" => "cart-button-color",
        "name" => "Цвет кнопки",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_green" => "Зелёный",
            "payqr-button_blue" => "Синий",
            "payqr-button_orange" => "Оранжевый",
            "payqr-button_red" => "Красный"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-cart",
    ),
    array(
        "key" => "cart-button-form",
        "name" => "Округление краев кнопки",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_sharp" => "без округления",
            "payqr-button_rude" => "минимальное округление",
            "payqr-button_soft" => "мягкое округление",
            "payqr-button_sleek" => "значительное округление",
            "payqr-button_oval" => "максимальное округление"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-cart",
    ),
    array(
        "key" => "cart-button-shadow",
        "name" => "Тень кнопки",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_shadow" => "включена",
            "payqr-button_noshadow" => "отключена"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-cart",
    ),
    array(
        "key" => "cart-button-gradient",
        "name" => "Градиент кнопки",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_flat" => "отключен",
            "payqr-button_gradient" => "включен"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-cart",
    ),
    array(
        "key" => "cart-button-text-size",
        "name" => "Размер текста кнопки",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_text-small" => "мелко",
            "payqr-button_text-medium" => "средне",
            "payqr-button_text-large" => "крупно"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-cart",
    ),
    array(
        "key" => "cart-button-text-width",
        "name" => "Текст кнопки жирным",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_text-normal" => "отключен",
            "payqr-button_text-bold" => "включен"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-cart",
    ),
    array(
        "key" => "cart-button-text-case",
        "name" => "Регистр текста кнопки",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_text-lowercase" => "нижний",
            "payqr-button_text-standartcase" => "стандартный",
            "payqr-button_text-uppercase" => "верхний"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-cart",
    ),
    array(
        "key" => "cart-button-height",
        "name" => "Высота кнопки",
        "value" => "auto",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-cart",
    ),
    array(
        "key" => "cart-button-width",
        "name" => "Ширина кнопки",
        "value" => "auto",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-cart",
    ),
    /*array(
        "key" => "button-show-on-product",
        "name" => "Показывать кнопку PayQR на страничке карточки товара",
        "value" => "",
        "possible_values" => array("Нет", "Да"),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-options",
    ),
    array(
        "key" => "product-button-color",
        "name" => "Цвет кнопки",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_green" => "Зелёный",
            "payqr-button_blue" => "Синий",
            "payqr-button_orange" => "Оранжевый",
            "payqr-button_red" => "Красный"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-product",
    ),
    array(
        "key" => "product-button-form",
        "name" => "Округление краев кнопки",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_sharp" => "без округления",
            "payqr-button_rude" => "минимальное округление",
            "payqr-button_soft" => "мягкое округление",
            "payqr-button_sleek" => "значительное округление",
            "payqr-button_oval" => "максимальное округление"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-product",
    ),
    array(
        "key" => "product-button-shadow",
        "name" => "Тень кнопки",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_shadow" => "включена",
            "payqr-button_noshadow" => "отключена"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-product",
    ),
    array(
        "key" => "product-button-gradient",
        "name" => "Градиент кнопки",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_flat" => "отключен",
            "payqr-button_gradient" => "включен"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-product",
    ),
    array(
        "key" => "product-button-text-size",
        "name" => "Размер текста кнопки",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_text-small" => "мелко",
            "payqr-button_text-medium" => "средне",
            "payqr-button_text-large" => "крупно"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-product",
    ),
    array(
        "key" => "product-button-text-width",
        "name" => "Текст кнопки жирным",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_text-normal" => "отключен",
            "payqr-button_text-bold" => "включен"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-product",
    ),
    array(
        "key" => "product-button-text-case",
        "name" => "Регистр текста кнопки",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_text-lowercase" => "нижний",
            "payqr-button_text-standartcase" => "стандартный",
            "payqr-button_text-uppercase" => "верхний"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-product",
    ),
    array(
        "key" => "product-button-height",
        "name" => "Высота кнопки",
        "value" => "auto",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-product",
    ),
    array(
        "key" => "product-button-width",
        "name" => "Ширина кнопки",
        "value" => "auto",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-product",
    ),*/
    array(
        "key" => "button-show-on-category",
        "name" => "Показывать кнопку PayQR на страничке категории товаров",
        "value" => "",
        "possible_values" => array("Нет", "Да"),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-options",
    ),
    array(
        "key" => "category-button-color",
        "name" => "Цвет кнопки",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_green" => "Зелёный",
            "payqr-button_blue" => "Синий",
            "payqr-button_orange" => "Оранжевый",
            "payqr-button_red" => "Красный"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-category",
    ),
    array(
        "key" => "category-button-form",
        "name" => "Округление краев кнопки",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_sharp" => "без округления",
            "payqr-button_rude" => "минимальное округление",
            "payqr-button_soft" => "мягкое округление",
            "payqr-button_sleek" => "значительное округление",
            "payqr-button_oval" => "максимальное округление"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-category",
    ),
    array(
        "key" => "category-button-shadow",
        "name" => "Тень кнопки",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_shadow" => "включена",
            "payqr-button_noshadow" => "отключена"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-category",
    ),
    array(
        "key" => "category-button-gradient",
        "name" => "Градиент кнопки",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_flat" => "отключен",
            "payqr-button_gradient" => "включен"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-category",
    ),
    array(
        "key" => "category-button-text-size",
        "name" => "Размер текста кнопки",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_text-small" => "мелко",
            "payqr-button_text-medium" => "средне",
            "payqr-button_text-large" => "крупно"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-category",
    ),
    array(
        "key" => "category-button-text-width",
        "name" => "Текст кнопки жирным",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_text-normal" => "отключен",
            "payqr-button_text-bold" => "включен"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-category",
    ),
    array(
        "key" => "category-button-text-case",
        "name" => "Регистр текста кнопки",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "payqr-button_text-lowercase" => "нижний",
            "payqr-button_text-standartcase" => "стандартный",
            "payqr-button_text-uppercase" => "верхний"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-category",
    ),
    array(
        "key" => "category-button-height",
        "name" => "Высота кнопки",
        "value" => "auto",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-category",
    ),
    array(
        "key" => "category-button-width",
        "name" => "Ширина кнопки",
        "value" => "auto",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "button-show-on-category",
    ),
    array(
        "key" => "required-options",
        "name" => "Запрашиваемые поля",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "",
    ),
    array(
        "key" => "data-firstname-required",
        "name" => "Запрашивать имя покупателя",
        "value" => "",
        "possible_values" => array(
            "deny" => "Нет",
            "required" => "Да"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "required-options",
    ),
    array(
        "key" => "data-lastname-required",
        "name" => "Запрашивать фамилию покупателя",
        "value" => "",
        "possible_values" => array(
            "deny" => "Нет",
            "required" => "Да"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "required-options",
    ),
    array(
        "key" => "data-middlename-required",
        "name" => "Запрашивать отчество покупателя",
        "value" => "",
        "possible_values" => array(
            "deny" => "Нет",
            "required" => "Да"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "required-options",
    ),
    array(
        "key" => "data-phone-required",
        "name" => "Запрашивать номер телефона покупателя",
        "value" => "",
        "possible_values" => array(
            "deny" => "Нет",
            "required" => "Да"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "required-options",
    ),
    array(
        "key" => "data-email-required",
        "name" => "Запрашивать email адрес покупателя",
        "value" => "",
        "possible_values" => array(
            "deny" => "Нет",
            "required" => "Да"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "required-options",
    ),
    array(
        "key" => "data-delivery-required",
        "name" => "Запрашивать адрес доставки",
        "value" => "",
        "possible_values" => array(
            "deny" => "Нет",
            "required" => "Да",
            "nonrequired" => "Не обязательно"
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "required-options",
    ),
    array(
        "key" => "data-deliverycases-required",
        "name" => "Могут ли быть в магазине способы доставки",
        "value" => "",
        "possible_values" => array(
            "deny" => "Нет",
            "required" => "Да",
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "required-options",
    ),
    array(
        "key" => "data-pickpoints-required",
        "name" => "Могут ли быть в магазине точки самовывоза",
        "value" => "",
        "possible_values" => array(
            "deny" => "Нет",
            "required" => "Да",
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "required-options",
    ),
    array(
        "key" => "data-promocode-required",
        "name" => "Требование запросить промо-код",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "deny" => "Нет",
            "nonrequired" => "Не обязательно",
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "required-options",
    ),
    array(
        "key" => "data-promocode-details-article",
        "name" => "Внутренний идентификатор типа промо-кодов",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "data-promocode-required",
    ),
    array(
        "key" => "data-promocode-details-description",
        "name" => "Собственное пояснение получателя денежных средств к полю ввода промо-кода",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "data-promocode-required",
    ),
    array(
        "key" => "data-promocard-required",
        "name" => "Предлагать покупателю указать номер карты лояльности",
        "value" => "",
        "possible_values" => array(
            "default" => "По умолчанию",
            "deny" => "Нет",
            "nonrequired" => "Не обязательно",
        ),
        "changable" => "1",
        "published" => "1",
        "parent" => "required-options",
    ),
    array(
        "key" => "data-promocard-details-article",
        "name" => "Внутренний идентификатор типа промо-кодов",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "data-promocard-required",
    ),
    array(
        "key" => "data-promocard-details-description",
        "name" => "Собственное пояснение получателя денежных средств к полю ввода промо-кода",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "data-promocard-required",
    ),

    array(
        "key" => "message-options",
        "name" => "Сообщения",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "",
    ),
    array(
        "key" => "message-invoice-order-creating",
        "name" => "Сообщение в ответ на уведомление invoice.order.creating",
        "value" => "",
        "possible_values" => array("Не отправлять", "Отправлять"),
        "changable" => "1",
        "published" => "1",
        "parent" => "message-options",
    ),
    array(
        "key" => "message-invoice-order-creating-article",
        "name" => "Артикул/внутренний идентификатор сообщения",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "message-invoice-order-creating",
    ),
    array(
        "key" => "message-invoice-order-creating-text",
        "name" => "Сообщение в покупке после ее совершения",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "message-invoice-order-creating",
    ),
    array(
        "key" => "message-invoice-order-creating-imageUrl",
        "name" => "URL изображения в покупке после ее совершения. Временная ссылка, доступна для скачивания минимум сутки",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "message-invoice-order-creating",
    ),
    array(
        "key" => "message-invoice-order-creating-url",
        "name" => "URL ссылка на сайт продавца в покупке после ее совершения. Ссылка срабатывает при нажатии на изображение, загруженное по imageUrl",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "message-invoice-order-creating",
    ),
    array(
        "key" => "message-invoice-paid",
        "name" => "Сообщение в ответ на уведомление invoice.paid",
        "value" => "",
        "possible_values" => array("Не отправлять", "Отправлять"),
        "changable" => "1",
        "published" => "1",
        "parent" => "message-options",
    ),
    array(
        "key" => "message-invoice-paid-article",
        "name" => "Артикул/внутренний идентификатор сообщения",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "message-invoice-paid",
    ),
    array(
        "key" => "message-invoice-paid-text",
        "name" => "Сообщение в покупке после ее совершения",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "message-invoice-paid",
    ),
    array(
        "key" => "message-invoice-paid-imageUrl",
        "name" => "URL изображения в покупке после ее совершения. Временная ссылка, доступна для скачивания минимум сутки",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "message-invoice-paid",
    ),
    array(
        "key" => "message-invoice-paid-url",
        "name" => "URL ссылка на сайт продавца в покупке после ее совершения. Ссылка срабатывает при нажатии на изображение, загруженное по imageUrl",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "message-invoice-paid",
    ),
    array(
        "key" => "message-invoice-reverted",
        "name" => "Сообщение в ответ на уведомление invoice.reverted",
        "value" => "",
        "possible_values" => array("Не отправлять", "Отправлять"),
        "changable" => "1",
        "published" => "1",
        "parent" => "message-options",
    ),
    array(
        "key" => "message-invoice-reverted-article",
        "name" => "Артикул/внутренний идентификатор сообщения",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "message-invoice-reverted",
    ),
    array(
        "key" => "message-invoice-reverted-text",
        "name" => "Сообщение в покупке после ее совершения",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "message-invoice-reverted",
    ),
    array(
        "key" => "message-invoice-reverted-imageUrl",
        "name" => "URL изображения в покупке после ее совершения. Временная ссылка, доступна для скачивания минимум сутки",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "message-invoice-reverted",
    ),
    array(
        "key" => "message-invoice-reverted-url",
        "name" => "URL ссылка на сайт продавца в покупке после ее совершения. Ссылка срабатывает при нажатии на изображение, загруженное по imageUrl",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "message-invoice-reverted",
    ),
    array(
        "key" => "order-options",
        "name" => "Статусы заказов",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "",
    ),
    array(
        "key" => "order-status-invoice-order-creating",
        "name" => "Статус заказа при обработке уведомления invoice.order.creating",
        "value" => "",
        "possible_values" => $module->getIOCStatusList(),
        "changable" => "1",
        "published" => "1",
        "parent" => "order-options",
    ),
    array(
        "key" => "order-status-invoice-paid",
        "name" => "Статус заказа при обработке уведомления invoice.paid",
        "value" => "",
        "possible_values" => $module->getIPStatusList(),
        "changable" => "1",
        "published" => "1",
        "parent" => "order-options",
    ),
    array(
        "key" => "order-status-invoice.cancelled",
        "name" => "Статус заказа при обработке уведомления invoice.cancelled",
        "value" => "",
        "possible_values" => $module->getICStatusList(),
        "changable" => "1",
        "published" => "1",
        "parent" => "order-options",
    ),
    array(
        "key" => "order-status-invoice.failed",
        "name" => "Статус заказа при обработке уведомления invoice.failed",
        "value" => "",
        "possible_values" => $module->getIFStatusList(),
        "changable" => "1",
        "published" => "1",
        "parent" => "order-options",
    ),
    array(
        "key" => "order-status-invoice-reverted",
        "name" => "Статус заказа при обработке уведомления invoice.reverted",
        "value" => "",
        "possible_values" => $module->getIRStatusList(),
        "changable" => "1",
        "published" => "1",
        "parent" => "order-options",
    ),
    array(
        "key" => "custom-options",
        "name" => "Пользовательские настройки",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "",
    ),
    array(
        "key" => "data-userdata",
        "name" => "Поле в кнопке data-userdata (любое значение)",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "custom-options",
    ),
    array(
        "key" => "custom-button",
        "name" => "Кастомизировать кнопку",
        "value" => "",
        "possible_values" => array("Нет", "Да"),
        "changable" => "1",
        "published" => "1",
        "parent" => "custom-options",
    ),
    array(
        "key" => "custom-button-name",
        "name" => "Новое имя кнопки",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "custom-button",
    ),
    array(
        "key" => "custom-button-classes",
        "name" => "Кастомные классы кнопки (через пробел)",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "custom-button",
    ),
    array(
        "key" => "custom-button-styles",
        "name" => "Кастомные стили кнопки (через точку с запятой, по правилам css)",
        "value" => "",
        "possible_values" => array(),
        "changable" => "1",
        "published" => "1",
        "parent" => "custom-button",
    ),
);